#                                              -*-makefile-*-

DIRS=\
	lib/9\
	libbio\
	lib/lex\
	libregexp\
	libmath\
    \
	mk\
	lex\
	yacc\
    \
	ar\
    \
    rc\

# mkconfig is included at this point to allow it to override
# the preceding declarations if need be

<mkconfig

all:V:		all-Posix
clean:V:	clean-Posix
install:V:	install-Posix
installall:V:	installall-Posix
nuke:V:		nuke-Posix

cleandist:V: clean
	rm -f $ROOT/$OBJDIR/lib/lib*.a

nukedist:V: nuke
	rm -f $ROOT/$OBJDIR/bin/*.exe
	rm -f $ROOT/$OBJDIR/lib/lib*.a

&-Posix:QV:
	for(j in $DIRS){
		echo '(cd '^$j^'; mk $MKFLAGS $stem)'
		{
			cd $j
			mk $MKFLAGS $stem
		} || exit 1
	}

&-Plan9:QV:
	for (j in $DIRS)
	{
		echo '@{builtin cd' $j '; mk $MKFLAGS $stem}'
		@{builtin cd $j; mk $MKFLAGS $stem }
	}

# Convenience targets

Plan9-% plan9-%:V:
	mk 'SYSHOST=Plan9' 'OBJTYPE=386' $stem

Linux-% linux-%:V:
	mk 'SYSHOST=Linux' 'OBJTYPE=386' $stem
